### ISSUE TITLE
libkrun is leaking TCP sockets

### ISSUE THREAD

**Issue by blenessy** [containers/libkrun#112]
I am trying to run an [avalanchego 1.9.7](https://github.com/ava-labs/avalanchego/releases/tag/v1.9.7) node in an AMD SEV-ES TEE.
The app in question is a non-validating node in the Avalanche (P2P) network. Anybody can run this without investing in Avalanche. Avalanche nodes "discover" each over TCP port 9650 (in my case 9750). A node typically connects to 1000+ other nodes (I had to bump the NOFILE limit to 32768 - both for the VMM and in the guest TEE). 

My node seems to be working well for about 24 hours - the only thing off is:

1. every 20-30 the HTTP request (e.g. the [health api](https://docs.avax.network/apis/avalanchego/apis/health)) is delayed 10-45 seconds
2. there are frequent (seconds) `deferring proxy removal` warnings in libkrun logs
3. occasional (minutes) `stream: unhandled op` warnings with VSOCK_OP_RST 

After approx 24h. I can no longer reach my node over HTTP:
- I can see the thousands of TCP sockets in state `CLOSE-WAIT`.
- In libkrun logs this shows up frequently now: ` ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq`
- I can no longer connect to my TEE app over e.g. HTTP (not even SYN goes through to libkrun)

**The libkrun host system**
- AMD EPYC 7302P (SEV FW: 0.24 build 17)
- (up-to-date) debian bullseye backports kernel: `6.0.12-1~bpo11+1`

**The guest system**
- libkrun 1.4.9
- libkrunfw 3.9.0

<hr/>

Socket status on libkrun host:

```shell
ss -sp --tcp state CLOSE-WAIT
Total: 8294
TCP:   11475 (estab 1122, closed 5650, orphaned 0, timewait 5)

Transport Total     IP        IPv6
RAW       0         0         0        
UDP       1         1         0        
TCP       5825      5824      1        
INET      5826      5825      1        
FRAG      0         0         0        

Recv-Q Send-Q Local Address:Port     Peer Address:Port Process                                   
293    0          127.0.0.1:9750        127.0.0.1:40636 users:(("libkrun VM",pid=245580,fd=5493))
293    0          127.0.0.1:9750        127.0.0.1:33738 users:(("libkrun VM",pid=245580,fd=5756))
293    0          127.0.0.1:9750        127.0.0.1:36756 users:(("libkrun VM",pid=245580,fd=2101))
293    0          127.0.0.1:9750        127.0.0.1:56618 users:(("libkrun VM",pid=245580,fd=1872))
293    0          127.0.0.1:9750        127.0.0.1:51638 users:(("libkrun VM",pid=245580,fd=3849))
293    0          127.0.0.1:9750        127.0.0.1:42248 users:(("libkrun VM",pid=245580,fd=6794))
...
```

libkrun logs when avalanchego is no longer reachable on HTTP:

```shell
[2023-01-28T13:40:15Z ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq
[2023-01-28T13:40:16Z ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq
[2023-01-28T13:40:17Z ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq
[2023-01-28T13:40:18Z ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq
[2023-01-28T13:40:18Z ERROR devices::virtio::vsock::muxer] couldn't push pkt to queue, adding it to rxq
```

Socket leak rate over time:

![image](https://user-images.githubusercontent.com/5358256/215269893-b8fe194e-7caf-4823-b71c-247b63e4fb39.png)

**Comment by slp** [comment]
@blenessy thanks a lot for the detailed report. I agree this looks like a socket leak, when `TCP_inuse` grows it's clearly reflected in `TCP_alloc`, but when `TCP_inuse` decreases there's no drop in `TCP_alloc`.

I'm going to try to reproduce this issue myself and see if I can locate the root cause.

**Comment by blenessy** [comment]
Thanks for looking into this @slp. I should have mentioned that if you start from "genesis" (no Avalanche network history) it will likely take days for your node to catch up with the network. By enabling [State Sync](https://docs.avax.network/nodes/maintain/chain-config-flags#state-sync) you will catch up in a matter of hours.

Although the symptom above implies it (`deferring proxy removal`) multiple CPUs, I want make it clear that the TEE is configured with  8 CPUs and 16 GiB RAM. Nevertheless I expect this to be reproducible with less CPU cores/memory too.

With that said, I have also been trying to narrow in on the problem. **I cannot reproduce it if my TEE is limited to 1 CPU**  (you can see the num open sockers are constant over the week). So the leak seems to be connected multi-CPU use-cases. I am suspecting the [reaper](https://github.com/containers/libkrun/blob/main/src/devices/src/virtio/vsock/reaper.rs) at this point. 

The `timeout` given to [recv_timeout](https://github.com/containers/libkrun/blob/main/src/devices/src/virtio/vsock/reaper.rs#L57) seems wrong... currently you wait for `lowest_elapsed` or `Duration::MAX`. I think the actual intension was to sleep to (5s - `highest_elapsed`) or `Duration::MAX`. However, I don't really see how fix that would solve this problem. Nevertheless, I will try a fix and see if it helps.
