### ISSUE TITLE
Windows host support?

### ISSUE THREAD

**Issue by mwcampbell** [containers/libkrun#147]
How crazy would it be to try to support Windows as a host OS, via the Windows Hypervisor Platform? How pervasive is the assumption of a Unix-like host OS? I suppose the most challenging part would be filesystem support.

**Comment by slp** [comment]
I honestly don't know. I'm aware there's *some* support for Windows on various of the rust-vmm crates, but can't say to which extent.

Filesystem support would be hard, but there's already a free software virtio-fs implementation for Windows, so it's doable. We also depend heavily on epoll (kqueue for macOS) which will need to replaced with something equivalent on Win32.
