### ISSUE TITLE
Example binary "chroot_vm" can't find libkrun.so on Fedora 32

### ISSUE THREAD

**Issue by mgamal** [containers/libkrun#2]
Compiled libkrunfw and libkrun with the instructions in the README file. However, when trying:

$ ./chroot_vm rootfs/ /bin/sh
./chroot_vm: error while loading shared libraries: libkrun.so: cannot open shared object file: No such file or directory

**Comment by slp** [comment]
It's possible that the libraries where installed into `/usr/local/lib` or `/usr/local/lib64`, and that location is not configured in your distribution's `/etc/ld.so.conf`. Could you please try with something like this:

```
$ LD_LIBRARY_PATH=/usr/local/lib ./chroot_vm rootfs/ /bin/sh
```

or

```
$ LD_LIBRARY_PATH=/usr/local/lib64 ./chroot_vm rootfs/ /bin/sh
```

**Comment by mgamal** [comment]
Using 
`$ LD_LIBRARY_PATH=/usr/local/lib64 ./chroot_vm rootfs/ /bin/sh`

solves the problem.

Thanks

**Comment by slp** [comment]
> Using
> `$ LD_LIBRARY_PATH=/usr/local/lib64 ./chroot_vm rootfs/ /bin/sh`
> 
> solves the problem.
> 
> Thanks

Great! I'm going to document this problem in README.md
