### ISSUE TITLE
examples/chroot_vm failing

### ISSUE THREAD

**Issue by tylerfanelli** [containers/libkrun#216]
With latest `libkfrunfw`, the `chroot_vm` example (instructions shown in README) fails with a `Segmentation fault`.

**Comment by slp** [comment]
Can't reproduce it here. Can you give me your build options for both libkrun and libkrunfw? Also, please try to generate a backtrace for either the core dump or live. An strace may also help.

**Comment by tylerfanelli** [comment]
Closing this as issue as it was likely due to a libkrunfw update between 4.0.0 and latest breaking something w/r/t SEV-SNP. We can discuss this in the libkrunfw issues.
