### ISSUE TITLE
init: consider mkdir the mount directories

### ISSUE THREAD

**Issue by wainersm** [containers/libkrun#23]
The init executable is going to mount some filesystems on the guest (proc, sysfs, and so on). If the rootfs doesn't have, say, `/proc' then the operation fails.

It can be reproduced with the `chroot_vm` program and the rootfs made from a busybox container.

Should some (or all) of those mount point directories be created?

**Comment by slp** [comment]
That's an interesting question. I'd say a path that's missing those directory doesn't qualify as a valid root filesystem. On one hand, extending `init` to create those directories it's just a matter of a adding some simple syscalls, but on the other, that would go against the minimalist approach that I'm trying to maintain in `libkrun`.

I think I'm more inclined to not add those syscalls for the moment, and reconsider this if we find a use case that justifies the cost.

**Comment by wainersm** [comment]
@slp yeah, more syscalls would increase the time to boot I guess. Maybe one thing that can be done rather, is to document the expect rootfs layout.
