### ISSUE TITLE
Remove libfdt dependency

### ISSUE THREAD

**Issue by slp** [containers/libkrun#30]
crosvm has reimplemented the functionality required from libfdt into a Rust. Consider importing that code to remove our dependency on libfdt.

https://chromium-review.googlesource.com/c/chromiumos/platform/crosvm/+/2713569/8/arch/src/fdt.rs

**Comment by andreeaflorescu** [comment]
This is published now as part of rust-vmm, you can consume it as a crate if you wish: https://crates.io/crates/vm-fdt
