### ISSUE TITLE
Device passthrough

### ISSUE THREAD

**Issue by 3XX0** [containers/libkrun#32]
Is there any plan to support device passthrough through VFIO?

**Comment by slp** [comment]
Supporting VFIO would also require implementing support for PCI and, possibly, ACPI. While I don't have plans to work on it on the short term, I'd be in favor of adding that as an optional feature.

**Comment by 3XX0** [comment]
Right, looks like Cloud hypervisor and Firecracker have implemented some of it and I was hoping it could simply be reused through rust-vmm, but it looks like none of it is really there at the moment.

**Comment by slp** [comment]
I think there are plans to have virtio-pci support in rust-vmm crates, but in any case, porting that support from CH or Firecracker to libkrun is a relatively easy task, though a bit costly in time.

**Comment by slp** [comment]
We don't have plans to support device passthrough in the short term. Closing this one.
