### ISSUE TITLE
AMD SEV-SNP support

### ISSUE THREAD

**Issue by hstr0** [containers/libkrun#40]
Does libkrun support AMD SEV-SNP?

**Comment by tylerfanelli** [comment]
@hstr0, SEV-SNP is currently in the process of being supported in libkrun. See #82 for an implementation that allows for booting unattested SNP guests. Attestation support is currently a WIP.

**Comment by tylerfanelli** [comment]
@hstr0 libkrun SEV-SNP support is now upstream, see #82

**Comment by hstr0** [comment]
> @hstr0 libkrun SEV-SNP support is now upstream, see #82

Good news! Thanks!
