### ISSUE TITLE
Container stops without error when many env variables specified

### ISSUE THREAD

**Issue by Agalin** [containers/libkrun#93]
When running a container through podman/crun in krun mode it's not possible to specify more than 26 environment variables.

If more variables are specified container exits (without any visible errors).

Environment:
Debian 11
libkrun built from #92
libkrunfw 3.8.1
Both self-built without any special flags.

**Comment by Agalin** [comment]
Awesome! I feared it would require a huge reimplementation in krun (didn't check sev-related code, didn't even know that `tee` refers to it 😓).
That would also fix #94 and make #95 a non-issue I believe.

**Comment by slp** [comment]
Recent versions of libkrun read the environment variables from a file, so this should no longer be reproducible. Please feel free to reopen this one if the issue persists.
