### ISSUE TITLE
upgrade lru from "0.6.3" to  ">=0.7.1"

### ISSUE THREAD

**Issue by aboe76** [containers/libkrun#98]
When I was trying to build libkrun 1.4.8 package in obs, I got the following warning
RUSTSEC-2021-0130 -> crate: lru, cvss: None, class: ['memory-corruption']

see https://rustsec.org/advisories/RUSTSEC-2021-0130.html

can this be update >=0.7.1

this is the location:
https://github.com/containers/libkrun/blob/4c108e66fb9d077bb4d6a34702bbaf74ab1de8db/src/devices/Cargo.toml#L17

**Comment by fcrozat** [comment]
Still valid in 1.4.10

**Comment by aboe76** [comment]
@fcrozat thanks for bringing attention back, @tylerfanelli thanks for fixing
